import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Stack, Typography } from '@mui/material'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack alignItems="center" spacing={4}>
        <Box
          sx={{
            width: 300,
            height: 300,
            backgroundColor: 'primary.dark',
            '&:hover': {
              backgroundColor: 'primary.main',
              opacity: [0.9, 0.8, 0.7],
            },
          }}
        >
          <Typography variant="h2" component="h1">
            h1. Heading
          </Typography>
          ;
        </Box>
        <Box
          sx={{
            width: 300,
            height: 300,
            backgroundColor: 'primary.main',
            '&:hover': {
              backgroundColor: 'primary.light',
              opacity: [0.9, 0.8, 0.7],
            },
          }}
        >
          <Typography variant="h2" component="h1">
            h1. Heading
          </Typography>
          ;
        </Box>
        <Box
          sx={{
            width: 300,
            height: 300,
            backgroundColor: 'secondary.main',
            '&:hover': {
              backgroundColor: 'secondary.dark',
              opacity: [0.9, 0.8, 0.7],
            },
          }}
        >
          <Typography variant="h2" component="h1">
            h1. Heading
          </Typography>
          ;
        </Box>
      </Stack>
    </div>
  )
}

export default Home
